# Generated by Django 4.0.3 on 2022-04-15 16:21

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=sqlalchemy.sql.expression.true)),
                ('userId', models.CharField(max_length=200, null=sqlalchemy.sql.expression.true)),
                ('password', models.CharField(max_length=50, null=sqlalchemy.sql.expression.true)),
            ],
        ),
    ]
