# Generated by Django 4.0.3 on 2022-04-15 17:03

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBooked', models.DateTimeField(auto_now_add=True, null=sqlalchemy.sql.expression.true)),
                ('timerslots', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=sqlalchemy.sql.expression.true)),
                ('userId', models.CharField(max_length=200, null=sqlalchemy.sql.expression.true)),
                ('password', models.CharField(max_length=50, null=sqlalchemy.sql.expression.true)),
                ('email', models.EmailField(max_length=254, null=sqlalchemy.sql.expression.true)),
            ],
        ),
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBooked', models.DateTimeField(auto_now_add=True, null=sqlalchemy.sql.expression.true)),
                ('timerslots', models.IntegerField()),
                ('cName', models.CharField(max_length=200, null=sqlalchemy.sql.expression.true)),
                ('userId', models.CharField(max_length=200, null=sqlalchemy.sql.expression.true)),
                ('email', models.EmailField(max_length=254, null=sqlalchemy.sql.expression.true)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isBooked', models.BooleanField(default=sqlalchemy.sql.expression.false)),
            ],
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalRooms', models.IntegerField()),
                ('timeslots', models.CharField(choices=[('fullDay', 'fullday'), ('6am to 10am', '6am to 10am'), ('10am to 3pm', '10am to 3pm'), ('3pm to 10pm', '3pm to 10pm'), ('10pm to 6am', '10pm to 6am')], max_length=200)),
                ('advanceBooking', models.CharField(choices=[('oneday', 'oneday'), ('twoday', 'twoday'), ('threeday', 'threeday'), ('fourDay', 'fourday'), ('fiveDay', 'fiveday')], max_length=200)),
            ],
        ),
    ]
