# Generated by Django 4.0.3 on 2022-04-15 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_records_cname_remove_records_datebooked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='timerslots',
        ),
        migrations.AddField(
            model_name='booking',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.rules'),
        ),
    ]
