# Generated by Django 4.0.3 on 2022-04-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_booking_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customers'),
        ),
    ]
